services:
  db:
    image: postgres:16-alpine
    container_name: artefakt04-db
    environment:
      POSTGRES_DB: cloud_app
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./backend/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d cloud_app"]
      interval: 5s
      timeout: 5s
      retries: 10

  backend:
    build:
      context: ./backend
    container_name: artefakt04-backend
    environment:
      PORT: 8081
      DATABASE_URL: postgres://postgres:postgres@db:5432/cloud_app
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8081:8081"

volumes:
  db_data:
